# Generated by Django 4.2.16 on 2024-10-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_base_unit_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
