# Generated by Django 4.2.16 on 2024-11-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('PARTIALLY PAID', 'PARTIALLY PAID')], max_length=50, null=True),
        ),
    ]
