# Generated by Django 4.2.16 on 2024-10-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_total_base_unit_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('PARTIALLY PAID', 'PARTIALLY PAID')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_man',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.deliveryman'),
        ),
    ]
