# Generated by Django 4.2.16 on 2024-11-03 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_purchaseorder_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(auto_now_add=True)),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('returned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_status', models.CharField(choices=[('REFUNDED', 'REFUNDED'), ('PARTIALLY REFUNDED', 'PARTIALLY REFUNDED')], max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='core.purchaseorder')),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_products', to='core.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderReturnProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('purchase_order_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_products', to='core.purchaseorderreturn')),
            ],
        ),
    ]
