# Generated by Django 4.2.16 on 2024-10-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_financialreport_generalledger_inventorybatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='purchase_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.purchaseorder'),
            preserve_default=False,
        ),
    ]
