# Generated by Django 4.2.16 on 2024-10-15 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('core', '0007_purchaseorderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_man',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuration.bookingman'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuration.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.supplier'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
