# Generated by Django 4.2.16 on 2024-10-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('core', '0008_order_booking_man_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuration.supplier'),
            preserve_default=False,
        ),
    ]
