# Generated by Django 4.2.16 on 2024-10-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_backorder',
            field=models.BooleanField(default=False),
        ),
    ]
