# Generated by Django 4.2.16 on 2024-12-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_category_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('site_url', models.CharField(max_length=255)),
                ('site_admin_url', models.CharField(blank=True, max_length=255, null=True)),
                ('authorization_key', models.CharField(max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(max_length=255)),
                ('product_synced', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductWebsites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_product_id', models.CharField(max_length=255)),
                ('inventory_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('website_platform_response', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_integrations.websites')),
            ],
        ),
    ]
